server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?characterEncoding=utf8&useSSl=false
    username: root
    password: 718609
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html
#      static-path-pattern: /**
#  resources:
#    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources